'\" t
.\"     Title: yaz-record-iconv
.\"    Author: Index Data
.\" Generator: DocBook XSL Stylesheets v1.79.1 <http://docbook.sf.net/>
.\"      Date: 05/04/2018
.\"    Manual: Commands
.\"    Source: YAZ 5.25.0
.\"  Language: English
.\"
.TH "YAZ\-RECORD\-ICONV" "1" "05/04/2018" "YAZ 5.25.0" "Commands"
.\" -----------------------------------------------------------------
.\" * Define some portability stuff
.\" -----------------------------------------------------------------
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.\" http://bugs.debian.org/507673
.\" http://lists.gnu.org/archive/html/groff/2009-02/msg00013.html
.\" ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
.ie \n(.g .ds Aq \(aq
.el       .ds Aq '
.\" -----------------------------------------------------------------
.\" * set default formatting
.\" -----------------------------------------------------------------
.\" disable hyphenation
.nh
.\" disable justification (adjust text to left margin only)
.ad l
.\" -----------------------------------------------------------------
.\" * MAIN CONTENT STARTS HERE *
.\" -----------------------------------------------------------------
.SH "NAME"
yaz-record-conv \- YAZ Record Conversion Utility
.SH "SYNOPSIS"
.HP \w'\fByaz\-record\-conv\fR\ 'u
\fByaz\-record\-conv\fR [\fB\-v\ \fR\fB\fIloglevel\fR\fR] [\fIconfig\fR] [\fIfname\fR...]
.SH "DESCRIPTION"
.PP
\fByaz\-record\-conv\fR
is a program that exercises the record conversion sub system\&. Refer to record_conv\&.h header\&.
.SH "OPTIONS"
.PP
\-v \fIlevel\fR
.RS 4
Sets the LOG level to
\fIlevel\fR\&. Level is a sequence of tokens separated by comma\&. Each token is a integer or a named LOG item \- one of
fatal,
debug,
warn,
log,
malloc,
all,
none\&.
.RE
.SH "EXAMPLES"
.PP
The following backend configuration converts MARC records (ISO2709) to Dublin\-Core XML\&.
.sp
.if n \{\
.RS 4
.\}
.nf
    <backend name="F" syntax="usmarc">
      <marc inputcharset="marc\-8" inputformat="marc" outputformat="marcxml"/>
      <xslt stylesheet="\&.\&./etc/MARC21slim2DC\&.xsl"/>
    </backend>
    
 
.fi
.if n \{\
.RE
.\}
.PP
We can convert one of the sample records from YAZ\*(Aq test directory with:
.sp
.if n \{\
.RS 4
.\}
.nf
$ \&.\&./util/yaz\-record\-conv record\-conv\-conf\&.xml marc6\&.marc
<?xml version="1\&.0"?>
<dc:dc xmlns:dc="http://purl\&.org/dc/elements/1\&.1/">
  <dc:title>How to program a computer</dc:title>
  <dc:creator>
    Jack Collins
  </dc:creator>
  <dc:type>text</dc:type>
  <dc:publisher>Penguin</dc:publisher>
  <dc:language>eng</dc:language>
</dc:dc>

 
.fi
.if n \{\
.RE
.\}
.sp
.SH "FILES"
.PP
record_conv\&.h
.SH "SEE ALSO"
.PP
yaz(7)
.SH "AUTHORS"
.PP
\fBIndex Data\fR
